set nocompatible              " be iMproved, required
set nu
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
set hlsearch
set rtp+=~/.vim/bundle/Vundle.vim

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

filetype on
filetype off                  " required

syntax on

nnoremap <C-L> :nohlsearch<CR><C-L>

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
" Plugin 'git://git.wincent.com/command-t.git'
Plugin 'https://github.com/kien/ctrlp.vim'
Plugin 'tpope/vim-surround'
Plugin 'rizzatti/dash.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tomtom/tcomment_vim'
Plugin 'mustache/vim-mustache-handlebars'

call vundle#end()            " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
