set nocompatible " be iMproved

" For vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

" Dependencies of snipmate
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'honza/vim-snippets'

Bundle 'garbas/vim-snipmate'     " Snippets for for expression autocomplete
Bundle 'tpope/vim-fugitive'      " Git tools
Bundle 'gmarik/vundle'           " Dependency management
Bundle 'tpope/vim-rails'         " Rails
Bundle 'rizzatti/dash.vim'       " Dash documentation
Bundle 'tomtom/tcomment_vim'     " Commenting and uncommenting
Bundle 'vim-ruby/vim-ruby'       " Vim Ruby
Bundle 'tpope/vim-surround'      " Code surround
" Bundle 'jiangmiao/auto-pairs'  " Autogenerate pairs for brackets
Bundle 'ervandew/supertab'       " Tab completions
Bundle 'kien/ctrlp.vim'          " Fuzzy finder for vim (CTRL + P)
Bundle 'scrooloose/nerdtree'     " Navigation tree
Bundle 'plasticboy/vim-markdown' " Markdown syntax highlighting
Bundle 'mustache/vim-mustache-handlebars' " Mustache Handlebars syntax highlighting

set autoindent   " Use autoindenting
set rnu          " Use relative line numbers
set hlsearch     " High search areas
set incsearch    " Search incrementally as you type
set ignorecase   " Ignore case in the file
set smartcase    " Smart case detection

set clipboard=unnamed " Use system clipboard

let mapleader=','     " Use comma as leader key

" Remove highlights with leader + enter
nmap <Leader><CR> :nohlsearch<CR>

" Open and close Nerdtree with leader + q
nmap <leader>q :NERDTreeToggle<CR>

" Set tab stops and shift width
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Removing escape
ino jj <esc>
cno jj <c-c>
vno v <esc>

syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

augroup myfiletypes
  " Clear old autocmds in group
  autocmd!

  " autoindent with two spaces, always expand tabs
  autocmd FileType ruby,eruby,yaml,markdown set ai sw=2 sts=2 et
augroup END

" Show trailing whitespace and spaces before a tab
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

